FROM mcr.microsoft.com/devcontainers/python:3.12-trixie

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
